name: 'Setup Conan Dependencies'
description: 'Install and configure Conan dependencies for OpenStudio'

inputs:
  build-type:
    description: 'CMake build type (Release, Debug)'
    required: false
    default: 'Release'
  output-folder:
    description: 'Conan output folder'
    required: true
  conan-user-home:
    description: 'Conan user home directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Add Conan remotes
      shell: bash
      run: |
        # Configure Conan to ignore SSL certificates (Conan 2.x syntax)
        mkdir -p "$CONAN_USER_HOME/.conan2"
        echo "core.download:verify_ssl=False" >> "$CONAN_USER_HOME/.conan2/global.conf"
        echo "core:non_interactive=True" >> "$CONAN_USER_HOME/.conan2/global.conf"
        conan remote add conancenter https://center.conan.io --force
        conan remote add nrel-v2 https://conan.openstudio.net/artifactory/api/conan/conan-v2 --force

    - name: Setup Conan profile
      shell: bash
      run: |
        # Use the container path for Conan
        CONAN_HOME="/__w/OpenStudio/OpenStudio/.conan/.conan2"
        mkdir -p "$CONAN_HOME/profiles"
        
        # Check if profile exists in the workspace-specific location
        if [ ! -f "$CONAN_HOME/profiles/default" ]; then
          # Set CONAN_HOME and force detection to workspace-specific location
          export CONAN_HOME="$CONAN_HOME"
          conan profile detect --force
          # Ensure profile was created in the right location
          if [ ! -f "$CONAN_HOME/profiles/default" ] && [ -f "/github/home/.conan2/profiles/default" ]; then
            mkdir -p "$CONAN_HOME/profiles"
            cp "/github/home/.conan2/profiles/default" "$CONAN_HOME/profiles/default"
          fi
        else
          echo "Using existing Conan profile at $CONAN_HOME/profiles/default"
        fi

    - name: Install dependencies
      shell: bash
      run: |
        conan install . --output-folder=${{ inputs.output-folder }} --build=missing \
          -c tools.cmake.cmaketoolchain:generator=Ninja \
          -s compiler.cppstd=20 \
          -s build_type=${{ inputs.build-type }}