name: 'Setup Build Environment'
description: 'Setup system dependencies and compiler for OpenStudio build'

runs:
  using: 'composite'
  steps:
    - name: Setup system dependencies
      shell: bash
      run: |
        # Fix Kitware GPG key issue with retry logic and insecure connection
        for i in {1..3}; do
          if wget --no-check-certificate -O /tmp/kitware-key.asc https://apt.kitware.com/keys/kitware-archive-latest.asc; then
            gpg --dearmor /tmp/kitware-key.asc > /usr/share/keyrings/kitware-archive-keyring.gpg
            echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu jammy main' > /etc/apt/sources.list.d/kitware.list
            break
          else
            echo "Attempt $i failed, retrying..."
            sleep 2
          fi
        done
        
        # Update package list and install ccache
        apt-get update && apt-get install -y ccache

    - name: Setup compiler
      shell: bash
      run: |
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11
        update-alternatives --set gcc /usr/bin/gcc-11

    - name: Setup git configuration
      shell: bash
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git clean -fdx