name: 'Setup Build Environment'
description: 'Setup system dependencies and compiler for OpenStudio build'

runs:
  using: 'composite'
  steps:
    - name: Setup system dependencies
      shell: bash
      run: |
        # Fix Kitware GPG key issue
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
          gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu jammy main' | \
          tee /etc/apt/sources.list.d/kitware.list >/dev/null
        apt-get update && apt-get install -y ccache

    - name: Setup compiler
      shell: bash
      run: |
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11
        update-alternatives --set gcc /usr/bin/gcc-11

    - name: Setup git configuration
      shell: bash
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git clean -fdx